### PR TITLE
Added the  attribute to the CookieOptions

### PR DESCRIPTION
**Pull request by sfodje**

### CODE REVIEW

**Comment by ColinT** [comment]
You also need to change the `mergeOptions` function in `utils.ts`:
https://github.com/salemdar/ngx-cookie/blob/7c97205c4be1eeb8f23f663675c240d22f9b5a74/lib/src/lib/utils.ts#L15-L27

```ts
  export function mergeOptions(oldOptions: CookieOptions, newOptions?: CookieOptions): CookieOptions { 
    if (!newOptions) { 
      return oldOptions; 
    } 
    return { 
      /** other options */
      // ...

      // Add this line
      sameSite: isPresent(newOptions.sameSite) ? newOptions.sameSite : oldOptions.sameSite,
    }; 
  } 
```

**Comment by sfodje** [comment]
Thanks @ColinT 
I've made that change 👍

**Comment by freepowder** [comment]
@sfodje @ColinT  is there any plan of merge this issue ? Thanks in advance

**Comment by sfodje** [comment]
Sorry @freepowder , I am not a maintainer, so I can't merge the changes.

**Comment by ColinT** [comment]
@freepowder The maintainer is @salemdar .

@sfodje would you please request a review from them? Thanks.

For now you can make a local copy with the aforementioned changes and load them into your project that way.

**Pull request closed without merging**
